[prose]
ignore = ["_prose.yml", "config.yaml", "README.md", "dropbox/config.toml", "dropbox/data", "dropbox/layouts", "dropbox/themes", "dropbox/static"]
media = "static/img"
rooturl = ""
[prose.metadata]

[[dropbox/content/post]]
    name = "template"
    [dropbox/content/post.field]
        element = "hidden"
        value = "post-page.html"

[[dropbox/content/post]]
	name = "variant_id"
    [dropbox/content/post.field]
        element = "hidden"
        value = "1234ASD"

[[dropbox/content/post]]
	name = "custom_js"
    [dropbox/content/post.field]
        element = "hidden"
        value = "1234ASD"
    [[dropbox/content/post.value]]
        "hero-page.css"

[[dropbox/content/post]]
	name = "custom_css"
	[dropbox/content/post.field]
	 element = "hidden"
        value = "1234ASD"
    [[dropbox/content/post.value]]
        "hero-page.css"

[[dropbox/content/post]]
	name = "Date"
    [dropbox/content/post.field]
        element = "hidden"
        value = "CURRENT_DATETIME"

[[dropbox/content/post]]
	name = "title"
    [dropbox/content/post.field]
        element = "text"
        label = "Title"
        placeholder = "The Page Title"

[[dropbox/content/post]]
	name = "Tags"
    alterable = true
    [[dropbox/content/post.options]]
        name = "Dropbox"
        value = "Dropbox"

    [[dropbox/content/post.options]]
        name = "Post"
        value = "Post"

[[dropbox/content/post]]
    name = "published"
    [dropbox/content/post.field]
        element = "checkbox"
        value = true
        label = "Published?"
